---
# Internal variables for iroh-dns-server.

_iroh_dns_arch_map:
  x86_64: "x86_64-unknown-linux-gnu"
  amd64: "x86_64-unknown-linux-gnu"
  aarch64: "aarch64-unknown-linux-gnu"
  arm64: "aarch64-unknown-linux-gnu"

iroh_dns_release_basename: >-
  iroh-dns-server-v{{ iroh_dns_version }}-{{ iroh_dns_target }}
iroh_dns_tarball_url: "https://github.com/n0-computer/iroh/releases/download/v{{ iroh_dns_version }}/{{ iroh_dns_release_basename }}.tar.gz"

_iroh_dns_build_packages:
  Debian:
    - build-essential
    - git
    - curl
    - ca-certificates
    - pkg-config
    - libssl-dev
  RedHat:
    - gcc
    - gcc-c++
    - make
    - git
    - curl
    - ca-certificates
    - pkgconfig
    - openssl-devel
  Suse:
    - gcc
    - gcc-c++
    - make
    - git
    - curl
    - ca-certificates
    - pkg-config
    - libopenssl-devel
